name: Jekyll site CI

on:
  push:
    branches: 
      - gh-pages
      - master
  pull_request:
    branches: 
      - gh-pages
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
    - uses: helaili/jekyll-action
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
