name: Monthly Build

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    name: Create and push empty commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create an empty commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "Committing with comment: Automated Monthly Build"
        git commit -m "Monthly build - $" --allow-empty
    - name: Push empty commit
      run: |
        echo "Pushing to: github.com/$.git"
        git push "https://$:$@github.com/$.git" master
